// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wznfxtoydguuahyrzoex.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6bmZ4dG95ZGd1dWFoeXJ6b2V4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzNTU3OTgsImV4cCI6MjA1ODkzMTc5OH0.AJw8PErvNDcIKGx14D-FI8U_tGjZ1x4Avy0nwv6K5j0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);